### ISSUE TITLE
Can we have README with rules? 

### ISSUE THREAD

**Issue by Omkar-Ajnadkar** [IIITKalyaniFOSC/design-jam-2018#1]
Can anyone familiar with designing, explain in which format we have to create it and other stuff like size, dimensions, etc.?

**Comment by PulkitMishra** [comment]
@Omkar-Ajnadkar  Can you or maybe @anubhavp28  please create an empty readme file?
Empty repos can't be forked.

**Comment by anubhavp28** [comment]
I am sorry, I didn't knew whoever creates the repo, gets it's full control. I have added @PulkitMishra, @zeus0789 and @Satyam-TG as contributors now.

**Comment by Omkar-Ajnadkar** [comment]
I am saying about creating README in this repo...

**Comment by anubhavp28** [comment]
@Omkar-Ajnadkar Design Jam most preferably expects a vector art of the logo (designed with Adobe Illustrator or Inkspace). A raster image(designed with Adobe Photoshop , GIMP or any other tool) can also considered if the resolution is large enough (say width should be at least 1000px). IMO aspect ratio of the logo can be anything (although hasn't been a discussion on this yet).

**Comment by Satyam-TG** [comment]
Made a README

**Comment by blackbird71SR** [comment]
@anubhavp28 Add this to README so that  no one will be confused about same...
