### ISSUE TITLE
Ritika Kumari, 1st year (2017-21), 39/CSE/17069/267

### ISSUE THREAD

**Issue by riti1302** [IIITKalyaniFOSC/design-jam-2018#15]
# **My Submission**

As I can't find any astonishing design, so I came up with this mere simple degisn.

![fosc-jpg](https://user-images.githubusercontent.com/36573421/40267791-98ccebca-5b80-11e8-9271-4ca471027bb2.jpg)

## **Motivation**
Didn't find motivation from anywhere. Just browsing through some images and got slightly **O** shaped share icon, so decided to use it here.

## **What does the logo mean?**
As we know resource and data sharing is one of the key purpose of open source, so I replaced the alphabet **O** in the logo by 4 sharing icon forming an **O**.

## **About Me**
Name- [Ritika Kumari](https://github.com/riti1302)
Current Year- Ist (2017-21)

## **Image Type**

- [x] Raster Image

- [x] Vector Image

### **File Supplied**

  * [FOSC-AI.ai](https://github.com/riti1302/design-jam/blob/2018/submissions/riti1302/FOSC-AI.ai)
  * [FOSC-PNG.png](https://github.com/riti1302/design-jam/blob/2018/submissions/riti1302/FOSC-PNG.png)

**Comment by PulkitMishra** [comment]
Thanks for your submission @riti1302 . Looks awesome ^_^

**Comment by anubhavp28** [comment]
@riti1302 Thanks for participating!
