### ISSUE TITLE
Somnath Pal, 1st year (2017-21), 39/CSE/17085/283

### ISSUE THREAD

**Issue by WizArdZ3658** [IIITKalyaniFOSC/design-jam-2018#16]
# Inspiration
Logos should be unique, visually enticing and deliver its intended message to the target audience. Logos should be simple so that even a lay man can understand it . I spent a lot of time thinking about relevant typography and color combination (though i was limited by my knowledge in Adobe illus) . I also went through numerous websites, magazines etc about logos and all . 

![iiitk_foscjpgver](https://user-images.githubusercontent.com/38949406/40218356-7a5ba2a0-5a8e-11e8-9a66-75ab4ce766ca.jpg)

# About my Logo
I tried to keep it simple, used a good mix of colors and font styles . The background is textured grid of greenish-bluish cool color (idk the name for that color) and I used warm colors on that for the contrast . To make it look more as a communicating position b/w the viewers and the community I've placed this laptop in the center and a page with lines of code in it . The name is enclosed in angular brackets giving it a look of coding stuff :p  . 

# About Me
**Name** : Somnath Pal
**Year** : 1st year (2017-21)

# Image Types Supplied
Vector images
Raster images
   
# Download link
https://drive.google.com/open?id=1CD0QWkMzlcEehMNDfgqBvcTVl8bCP1-w
(guys I uploaded .png file , .ai file and .svg file in the drive, I tried to upload it here but there was some problem with the file size)

**Comment by abhishekti7** [comment]
@WizArdZ3658 great job man. The logo is visually very appealing. Thanks for participating bud.

**Comment by PulkitMishra** [comment]
Nice work there @WizArdZ3658 :)

**Comment by anubhavp28** [comment]
@WizArdZ3658 It is surely among the best we have received. Thanks mate!
