### ISSUE TITLE
Ratna Priya , 1st year (2017-21), 39/CSE/17065/263

### ISSUE THREAD

**Issue by Ratna04priya** [IIITKalyaniFOSC/design-jam-2018#17]
# Suggestions are welcome  ^_^

This one is indeed  a fussy one ! But shows a jolly work. 

![f o s c](https://user-images.githubusercontent.com/37251540/40053833-601d4afe-5860-11e8-81cd-4fc9995967bd.jpg)

Always be a bright learner  !!

![fosc 1](https://user-images.githubusercontent.com/37251540/40053857-7bbd199c-5860-11e8-9e62-78373610a9e1.jpg)

**Comment by anubhavp28** [comment]
@Ratna04priya Thanks for participating! You did a nice job.

**Comment by PulkitMishra** [comment]
@Ratna04priya looks great! Thanks for your submission :)

**Comment by satyamtg** [comment]
@Ratna04priya  Looks good. Thanks for participating.

**Comment by riti1302** [comment]
@Ratna04priya Surely you put a real hardwork there. Great job.
