### ISSUE TITLE
Sattam Ghosal, 1st Year (2017-21), 39/CSE/17076/274

### ISSUE THREAD

**Issue by ghosalsattam** [IIITKalyaniFOSC/design-jam-2018#18]
[logo fosc.pdf](https://github.com/IIITKalyaniFOSC/design-jam/files/2007959/logo.fosc.pdf)

**Comment by anubhavp28** [comment]
@ghosalsattam Nice job! Thanks for participating. :smile:

**Comment by satyamtg** [comment]
@ghosalsattam Thanks for participating. You did a good job.

**Comment by PulkitMishra** [comment]
@ghosalsattam nicely done. Thanks for participating buddy ^_^
