### ISSUE TITLE
Aditya Sujith Gudimetla, 1st Year (2017-21), 39/CSE/17009/207

### ISSUE THREAD

**Issue by CaptainLazarus** [IIITKalyaniFOSC/design-jam-2018#19]
![untitled 1 1](https://user-images.githubusercontent.com/35800668/40128282-dc0b73a4-594e-11e8-973d-faf1e5085a70.jpg)
![untitled 3](https://user-images.githubusercontent.com/35800668/40128284-dc46d9bc-594e-11e8-8ed7-2c08afbb77b8.jpg)

**Comment by CaptainLazarus** [comment]
Works better with a black background.

**Comment by PulkitMishra** [comment]
Good job man. @anubhavp28 what say now?

**Comment by abhishekti7** [comment]
Nice design and indeed works better with black background

**Comment by anubhavp28** [comment]
@PulkitMishra @CaptainLazarus Great work man! really you proved me wrong.
