### ISSUE TITLE
Subham, 1st year (2017-21), 39/CSE/17088/286

### ISSUE THREAD

**Issue by Subham2804** [IIITKalyaniFOSC/design-jam-2018#20]
Since it is all about sharing ideas among people ,my logo basically explains the whole mechanism
F: shown as a man serving
O:shown as setting icon is basically technology
S: made up with magnet and lightening bulb symbolizing ideas
C: is formed by we the people
so basically it mean
Serving technological ideas with people in order to attract and distribute ideas  for a bright Future!!
(Didn't find any suitable backgroung combination)

**Comment by Subham2804** [comment]
![focs_logo](https://user-images.githubusercontent.com/39151404/40272578-1cbbbbcc-5bcd-11e8-8f4a-f0149dd958d8.png)

**Comment by anubhavp28** [comment]
@Subham2804 Nice work!

**Comment by abhishekti7** [comment]
@Subham2804 Great job!!

**Comment by PulkitMishra** [comment]
@Subham2804 looks cool.

**Comment by satyamtg** [comment]
@Subham2804 Good work bro.
