### ISSUE TITLE
Ankur Konar, 1st Year (2017-21), (39/CSE/17017/215)

### ISSUE THREAD

**Issue by AnkurKonar** [IIITKalyaniFOSC/design-jam-2018#21]
![untitled-1](https://user-images.githubusercontent.com/30037050/40351018-0237f29a-5dc9-11e8-996c-358d994e0247.png)

This is my submission for the Design-jam.

Well, i wanted the logo to resemble what FOSC denotes.

f from facebook, and we all know that facebook is free and connected to over billions of users
o from the github logo that denotes open source.
s from the sublime text editor that allows us to edit code and everything.
c from C# which is an important part of the web development.

p.s. i know its kind of lame but it does resembles a lot. and i assure you there are no copyright issues.

**Comment by PulkitMishra** [comment]
@AnkurKonar nice try :3
