### ISSUE TITLE
Anish Kumar Kharwar, 1st year (2017-2021), 39/CSE/17016/214

### ISSUE THREAD

**Issue by anishk74** [IIITKalyaniFOSC/design-jam-2018#22]
![logo_fosc - copy](https://user-images.githubusercontent.com/32957008/40359794-9329d3be-5de1-11e8-900c-f213c04be5ec.png)

The logo should be simple to be understood and attractive as well.
This is my submission for Design-Jam FOSC.
I have tried to explain some things with the help of the logo.
F: F for first and first comes our IIIT KALYANI which has provided us the platform to come up and work together.
Just think what if you were not in IIIT KALYANI. Would it be that easier to participate in this contest or join us?
Of course not. We owe a lot to this institute. So this came first in my mind.
C: C represents the first programming language most of us(including me) came to know about.
Also a curious mind can easily find what the remaing part of the logo mean.
OS, Yes Operating System, the most important software that runs on your computer.
Whether it be multitasking, time-sharing, Embedded or RTOS, It has much importance our day to day life.
OS may also represent the android development, if the community is also going for that field.
That was all in my mind before desining the logo and I tried to implement most of these ideas also explaining with
the help of my logo.
FILE
I have submitted .svg file to Abhishek Tiwari.

**Comment by abhishekti7** [comment]
@anishk74 nice idea. Cool design.

**Comment by PulkitMishra** [comment]
@anishk74 Nice work man.

**Comment by satyamtg** [comment]
@anishk74 Good idea man.
