### ISSUE TITLE
Pratik Sagar, 1st Year(2017-2021), 39/CSE/17057/255

### ISSUE THREAD

**Issue by Pratik57** [IIITKalyaniFOSC/design-jam-2018#23]
![fosc1](https://user-images.githubusercontent.com/39158589/40422458-0b5e9d94-5ead-11e8-8583-436b1fc64c42.png)
![fosc2](https://user-images.githubusercontent.com/39158589/40422492-295cb22c-5ead-11e8-961e-7dbd2ecd0923.png)
![fosc3](https://user-images.githubusercontent.com/39158589/40422529-4869e798-5ead-11e8-9889-4bfe37447689.png)
![fosc4](https://user-images.githubusercontent.com/39158589/40422558-642b3220-5ead-11e8-85f6-e3b30a36bdf1.png)

**This is my submission(but actually not)**

- After watching all your dedication, i get motivated and try to participate in this design jam.

- This is all your work and i just place them (as this is contributed on open source).
   

- Actually, i can't chooce among the four, so upload them all.

- Required files 

https://drive.google.com/open?id=1rdMCJrbxCCUIuoDcLGbqzAZSqa7yztPK

**Comment by anubhavp28** [comment]
@Pratik57 Good work, man!

**Comment by PulkitMishra** [comment]
Thanks for participating @Pratik57 :) 
Keep learning. Keep participating.
