### ISSUE TITLE
Abhishek Tiwari, 1st year (2017-21) 39/CSE/17006/204

### ISSUE THREAD

**Issue by abhishekti7** [IIITKalyaniFOSC/design-jam-2018#4]
# My Submission

![fosc_zeus](https://user-images.githubusercontent.com/32027962/39958775-4ba39692-5625-11e8-9ea1-ef8ca183da92.png)

## Inspiration for the logo
I listed down all the things that came to my mind when I thought about FOSC. Basically I listed down all the things that the Free and Open Source Community stands for and I came up with this design.

- the symbol used in place of the letter 'O' in the logo stands for the two important virtues the founding fathers had in mind back then:

- 

1.  **Team Work/Contribution** -- in the symbol we see various hands working together to accomplish the task. This is one of the significant features of open source contribution; we all work together, contribute different unique features and accomplish goals, kinda like how the different background colors of the hands make the whole logo beautiful. Also, the different colored hands show that ANYONE can contribute to a code and that fosc is discrimination free.

2.  **Sharing** -- The unmistakable share logo in the centre of the symbol shows which feature of FOSC is at it's heart. Sharing is the attribute which makes FOSC so unique and admirable. We share pieces of code, pieces of knowledge freely and without any selfishness. Thus we try to eradicate the one fault which keeps us from greatness - selfishness and jealousy. 

- The unmistakable pac-man symbol from our childhood favourite game stylised as the letter 'C' stands for the fact is contribution to open source development is enjoyable and fun.

**P.S.**-- The blue background does not stand for anything. It simply looked good so I selected it.

# About Me

 Name-  **Abhishek Tiwari**
Current Year -- **1st (2017-2021)**

Image Type--

- [x] Vector Image
- [x] Raster Image

File Supplied:
* [fosc_zeus.ai](https://github.com/zeus0789/design-jam/blob/2018/submissions/zeus0789/fosc_zeus.ai)
* [fosc_zeus.png](https://github.com/zeus0789/design-jam/blob/2018/submissions/zeus0789/fosc_zeus.png)
* [fosc_zeus.svg](https://github.com/zeus0789/design-jam/blob/2018/submissions/zeus0789/fosc_zeus.svg)

**Comment by anubhavp28** [comment]
@zeus0789 _Thanks_

**Comment by satyamtg** [comment]
@zeus0789 Thanks for participating buddy.
