### ISSUE TITLE
Pulkit Mishra, 1st year (2017-21), 39/CSE/17060/258

### ISSUE THREAD

**Issue by PulkitMishra** [IIITKalyaniFOSC/design-jam-2018#5]
# My Submission

![fosc-logo1](https://user-images.githubusercontent.com/31157487/39956149-b91e7d86-55f8-11e8-8958-1f7d4099034e.png)

## About Me

Name : __[Pulkit Mishra](https://github.com/PulkitMishra)__  
Current Year : __1st Year (2017-2021)__ 

## Idea

A simple and elegant design based on a mantra I believe in : "Wear your identity on your sleeve." What do I mean by that? Well, go ahead and scan the QR code above.

File Supplied :
  * [fosc_logo1.eps](https://github.com/PulkitMishra/design-jam-2018/blob/master/submissions/PulkitMishra/fosc-logo1.eps)
  * [fosc_logo1.png](https://github.com/PulkitMishra/design-jam-2018/blob/master/submissions/PulkitMishra/fosc-logo1.png)

**Comment by anubhavp28** [comment]
@PulkitMishra  Thanks for participating! Nice work as usual, do you know why the QR code still worked, even when a good chunk of it is gone?

**Comment by satyamtg** [comment]
@PulkitMishra A working QR. Good idea. Thanks for participating.

**Comment by PulkitMishra** [comment]
@anubhavp28 Is it because the sections that contain data were not tampered with?
