### ISSUE TITLE
Rohan Chakraborty, 1st Year (2017-21), 39/CSE/17072/270

### ISSUE THREAD

**Issue by rohan-chakra** [IIITKalyaniFOSC/design-jam-2018#6]

**Comment by rohan-chakra** [comment]
# My Submission
This is a simple sketch of how I think the logo of IIIT Kalyani FOSC should look like. To start of with, the letters 'F' and 'S' are formed using binary numbers, which is the core language of computers.
The last letter 'C' is basically a path traced by a paper plane signifying the freedom of our imagination isn't limited to papers.
The most elaborate letter is the letter 'O' that is a globe with laptops revolving around it. It is no surprise that is what is happening in our planet and also in our community. Lastly, an airplane carries the banner of 'FOSC' representing no height is to great for us to reach at this community.
That's it, I tried to make it as simple and catchy as possible, hope all of you like it! ; )
![psx_20180516_002936](https://user-images.githubusercontent.com/39150396/40080049-732c902c-58a7-11e8-9cc0-e4d17228082d.jpg)

**Comment by anubhavp28** [comment]
@rohan-chakra Your skills with those hand-made sketches is phenomenal. Best of luck. Thanks for participating!

**Comment by PulkitMishra** [comment]
@rohan-chakra That has to be the best thing I've seen on the internet today. Awesome work. Kudos!

**Comment by satyamtg** [comment]
@rohan-chakra Thats nice. Thanks for participating.

**Comment by abhishekti7** [comment]
Nice job

**Comment by riti1302** [comment]
@rohan-chakra Always great with sketches. Impressive man
