### ISSUE TITLE
Jyotika Yadav, 1st year (2017-21), 39/CSE/17040/238

### ISSUE THREAD

**Issue by jay4jyotika** [IIITKalyaniFOSC/design-jam-2018#7]
# The Submission
![jay_fosc_logo](https://user-images.githubusercontent.com/36258525/40278357-8865d7ce-5c4d-11e8-85d2-db98663cfd0f.jpg)

# The Idea
The gears can't work if they aren't joined, or they are not "together". So it symbolizes teamwork. Yay.
And the cloud is an idea cloud, signifying the ideas that build FOSC. Yay.
**Ideas Working Together**

# The Links
<a href="https://github.com/jay4jyotika/design-jam/blob/2018/submissions/jay4yadav/jay_fosc_logo_png.png">the png<a>
<a href="https://github.com/jay4jyotika/design-jam/blob/2018/submissions/jay4yadav/jay_fosc_logo_svg.svg">the svg<a>

### From
Jyotika Yadav
1st Year (2017-21)

**Comment by PulkitMishra** [comment]
@jay4jyotika Nice thought process. Cool design. Awesome logo :)

**Comment by abhishekti7** [comment]
@jay4jyotika  nicely executed. Cool design.

**Comment by anubhavp28** [comment]
@jay4jyotika great work!
