### ISSUE TITLE
Sayantan Das, 1st Year (2017-21), 39/CSE/17079/277

### ISSUE THREAD

**Issue by sayantanDs** [IIITKalyaniFOSC/design-jam-2018#8]

**Comment by sayantanDs** [comment]
# My Submission
![fosc_logo_sayantan_raster_512x512](https://user-images.githubusercontent.com/39154403/39953602-29203c86-55cd-11e8-8b79-66ecf82faafa.png)
## Description
This logo is basically an arrangement of the letters **F O S C** rotated by 90 degrees. Also it happens to look like a guy thinking hard!!

![g851](https://user-images.githubusercontent.com/39154403/39953713-f915db70-55ce-11e8-81a1-082be0b16b45.png) 
The unique shape will make it **recognisable even in smaller sizes**.

[Link to vector image](https://github.com/IIITKalyaniFOSC/design-jam/blob/2018/submissions/sayantanDs/fosc_logo_Sayantan.svg)

### About Me
Name : **Sayantan Das**
Current Year: **1st Year (2017-2021)**

**Comment by PulkitMishra** [comment]
Looks cool 8)

**Comment by Pratik57** [comment]
(^0^)

**Comment by anubhavp28** [comment]
@sayantanDs Thanks for participating!

**Comment by PulkitMishra** [comment]
@sayantanDs Looks great man :D

**Comment by satyamtg** [comment]
@sayantanDs A good submission. Thanks for participating.
