### ISSUE TITLE
Anubhav Patel, 1st Year (2017-21), 39/CSE/17020/218

### ISSUE THREAD

**Issue by anubhavp28** [IIITKalyaniFOSC/design-jam-2018#9]
# My Submission
![Anubhav Patel](https://user-images.githubusercontent.com/29521514/39930843-6433a7aa-5559-11e8-9974-ab2cf475c817.png)

## Motivation
Since Github's launch in 2007, Github has provided a platform for Open Source and has heavily simplifed its work flow. Github provides, this nice "Histogram of Past Contribution" on the profile of its every user. My logo is essentially a similar histogram with 'FOSC' crafted over it. The idea came into my mind this morning, when I realised that I had just complete my 7 day streak of contributions. :smile:    

## About Me
Name : __Anubhav Dinesh Patel__  
Current Year : __1st Year (2017-2021)__ 

Image Type :  

- [x] Vector Image
- [x] Raster Image
  
File Supplied :
  * [fosc_logo.ai](https://github.com/anubhavp28/design-jam/blob/2018/anubhav/fosc_logo.ai)
  * [fosc_logo.png](https://github.com/anubhavp28/design-jam/blob/2018/anubhav/fosc_logo.png)

**Comment by AnkurKonar** [comment]
Make the corners dark. It is hard to read in the first attempt. But the idea was indeed awesome.

**Comment by anubhavp28** [comment]
@AnkurKonar Which corners are we talking about, corners of the characters or the grid?

**Comment by abhishekti7** [comment]
@anubhavp28 the idea is cool. 1 advice though: ctrl+A all the objects in the vector file and group them so that they function as a group. This makes scaling the logo easier.

**Comment by PulkitMishra** [comment]
Aaaaaaaaaa had done something similar :'(
Gotta scrap it now :(
though it didn't look as good as this xD

**Comment by anubhavp28** [comment]
@zeus0789 I will take care of that, right now I am fiddling with the design of the logo, maybe it can be made better.

**Comment by anubhavp28** [comment]
@anubhavp28 Hey myself, thanks for participating!

**Comment by satyamtg** [comment]
@anubhavp28 Your logo looks great. Thanks for participating.
